### ISSUE TITLE
Should be `import { slideToggle } from 'slidetoggle';` in README

### ISSUE THREAD

**Issue by panlina** [zgrybus/slideToggle#1]
Not `import slideToggle from 'slidetoggle';`.

**Comment by knofz-qt** [comment]
Will fix it. Thanks!

**Comment by zgrybus** [comment]
Gonna fix it. Thanks!

**Comment by zgrybus** [comment]
Fixed

**Comment by kachaj7** [comment]
Isn't fixed!

**Comment by zgrybus** [comment]
@kachaj7  @panlina 

Fixed. Sorry! I changed the bundling way. Feel free to use the newest version [2.0.1](https://github.com/zgrybus/slideToggle/releases/tag/v2.0.1)
