### ISSUE TITLE
Height does not appear to be 'auto' as advertised.

### ISSUE THREAD

**Issue by ahorn-ucd** [zgrybus/slideToggle#12]
<img width="1226" alt="height-not-auto" src="https://user-images.githubusercontent.com/27697001/121553910-92e32780-c9c6-11eb-89f2-68844473a1a1.png">

**Comment by zgrybus** [comment]
Hi.
I can't set `height: auto`, because this value can't be animated. Therefore, I set a value defined with pixels.
It imitates `height: auto` and the final `height` should be the same.

**Comment by ahorn-ucd** [comment]
The issue we are having is that you cannot put dynamic content withing the content area of a slide toggle because of the fixed height. You are correct that it can't animate without a fixed height but content gets cut off any element within changes size. 

Something like this could work so that this could be used for things like menus.

`// Remove the submenu inline height once it is finished animating so that
      // child submenus have room to grow.
      setTimeout(function () {
        menu.style.height = 'auto';
      }, 350);`

**Comment by zgrybus** [comment]
Okay, I will try to fix it.
Moreover, I've been thinking about changing the code in some way, because it's pretty outdated :)

**Comment by zgrybus** [comment]
@ahorn-ucd 
Hi! I guess, it has been fixed [here](https://github.com/zgrybus/slideToggle/tree/issue/12). 
I'm going to add unit tests and then I will release new version :)

**Comment by zgrybus** [comment]
Fixed in https://github.com/zgrybus/slideToggle/pull/14
