### ISSUE TITLE
Problem Importing into Angular 12

### ISSUE THREAD

**Issue by KailanySousa** [zgrybus/slideToggle#13]
Hi guys, 

I needed to use slidetoggle in an angular project in version 12, but when importing as shown by the documentation I got an error, which said that it was not possible to find the module reference.

I managed to import as follows in my .ts file:

`import { slideToggle } from 'slidetoggle/dist/esm';`

It would be nice if you had this option in the readme or validate this problem.

**Comment by maiconkistemmacher** [comment]
Thanks, it worked for me!

**Comment by Arthurferrera** [comment]
> Hi guys,
> 
> I needed to use slidetoggle in an angular project in version 12, but when importing as shown by the documentation I got an error, which said that it was not possible to find the module reference.
> 
> I managed to import as follows in my .ts file:
> 
> `import { slideToggle } from 'slidetoggle/dist/esm';`
> 
> It would be nice if you had this option in the readme or validate this problem.

Hello it works here too thank you

**Comment by moises-alphacode** [comment]
Thank you so much!

**Comment by zgrybus** [comment]
> Hi guys,
> 
> I needed to use slidetoggle in an angular project in version 12, but when importing as shown by the documentation I got an error, which said that it was not possible to find the module reference.
> 
> I managed to import as follows in my .ts file:
> 
> `import { slideToggle } from 'slidetoggle/dist/esm';`
> 
> It would be nice if you had this option in the readme or validate this problem.

Thanks.
I will fix it in the next version that I've been already working on.

**Comment by zgrybus** [comment]
Fixed in Fixed in https://github.com/zgrybus/slideToggle/pull/14
