### ISSUE TITLE
[FEATURE] Allow a way to detect if an animation is in progress or has finished

### ISSUE THREAD

**Issue by mrkmiller** [zgrybus/slideToggle#17]
In version 2 I could determine if an animation was still opening by using `element.dataset.slidetoggle === 'true'`. This was helpful to prevent double clicks. In v3 the data attribute turns to true as soon as the animation begins so there doesn't seem to be a way to determine when it finishes.

**Comment by zgrybus** [comment]
Is it enough for you, if I add `onAnimationStart: () => {}` and `onAnimationFinish: () => {}` to the `options`?

**Comment by mrkmiller** [comment]
Yeah, that should work fine. Thanks!

**Comment by zgrybus** [comment]
@mrkmiller Fixed in 3.1.0

**Comment by AlonsoK28** [comment]
Is possible to add the following callbacks?

```
onToggleOpen: () => {
   console.log('Element is minized')
} 
```
and
```
onClosed: () => {
   console.log('Element is maximized')} 
```

for example to add some classes when is open and remove it when is closed

**Comment by zgrybus** [comment]
Hi @AlonsoK28.
As I correctly understand, you wish to have two new callbacks.
1. `onClosed` which represented state, when element is closed ( has 0 height ).
2. `onOpened` which represented state, when element is opened ( has 100% height ).

**Comment by AlonsoK28** [comment]
> Hi @AlonsoK28. As I correctly understand, you wish to have two new callbacks.
> 
> 1. `onClosed` which represented state, when element is closed ( has 0 height ).
> 2. `onOpened` which represented state, when element is opened ( has 100% height ).

Yes, exactly, this could be handly in many scenarios 🎉

**Comment by AlonsoK28** [comment]
Adittionally is really needed to add `display: block;` in the item content to make sidleToggle functionality?

Because in some cases this can broke the structure mainly in Boostrap that use `display: flex;` and if you change it the desing will be broken

**Comment by zgrybus** [comment]
> Yes, exactly, this could be handly in many scenarios 🎉

Could you please create new issue? So I will link MR to it.
I would really appreciate that.

**Comment by zgrybus** [comment]
> Adittionally is really needed to add `display: block;` in the item content to make sidleToggle functionality?
> 
> Because in some cases this can broke the structure mainly in Boostrap that use `display: flex;` and if you change it the desing will be broken

I may add new option property:
```javascript
{
 displayStyle: 'block' | 'flex' | ..etc
}
```
