### ISSUE TITLE
Provide API status callbacks 

### ISSUE THREAD

**Issue by AlonsoK28** [zgrybus/slideToggle#23]
Could you provide in your API the following callbacks: 

```
onClosed which represented state, when element is closed ( has 0 height ).
onOpened which represented state, when element is opened ( has 100% height ).
```

It will be usefull mainly when using `toggle` function 🎯

**Comment by zgrybus** [comment]
@AlonsoK28 Released in https://github.com/zgrybus/slideToggle/releases/tag/v3.2.3

**Comment by AlonsoK28** [comment]
excellent for this project 💁‍♂️💁‍♂️💁‍♂️💁‍♂️💁‍♂️💁‍♂️ 🚀
