### ISSUE TITLE
display: block; style breaks boostrap template

### ISSUE THREAD

**Issue by AlonsoK28** [zgrybus/slideToggle#24]
Initial state
![image](https://user-images.githubusercontent.com/37458700/145632957-dd52b0be-2fd7-4e78-aad7-30e9a385c1bc.png)

Minimized state
![image](https://user-images.githubusercontent.com/37458700/145633011-dc18171c-67b7-4bca-9665-0aad4cbb22be.png)

Maximized state with `display: block;` (breaks template)
![image](https://user-images.githubusercontent.com/37458700/145633100-6c56cc18-cce9-416c-9c3f-4cbcdd3780f8.png)

I have fixed using `display: flex;`

**Comment by zgrybus** [comment]
@AlonsoK28 
Released in https://github.com/zgrybus/slideToggle/releases/tag/v3.2.4

**Comment by AlonsoK28** [comment]
awesome🎉🎉🎉🎉
